### ISSUE TITLE
Can't run testnet-v4 node

### ISSUE THREAD

**Issue by Enflow-io** [ovrclk/net#256]
I've pulled master branch and installed akash.

Next: 
```
./akash init enflow --chain-id testnet-v4
./akash keys add enflow
curl -s curl https://raw.githubusercontent.com/ovrclk/net/master/latest/genesis.json > ~/.akash/config/genesis.json
Next edited config.toml (https://github.com/lightiv/SkyNet/wiki/Akash-Seed-Node-Installation-Guide)
```

Next
` ./akash start`

But got error:

`panic: Any JSON doesn't have '@type'
`

And 
```
./akash validate-genesis
Error: error validating genesis file /Users/constantine/.akash/config/genesis.json: failed to unmarshal genutil genesis state: unknown field "gentxs" in types.GenesisState
```

So I think something wrong with akash version?

**Comment by Ropes** [comment]
Hey @Enflow-io, thanks for the bug report.

There are two issues at play here. 

* Akash binary release version, which I assume you pulled 'master' or recent release since you're using `akash` binary, which uses CosmosSDK 0.40+. This change came recently to `ovrclk/akash`, and breaks compatibility with the current mainnet and the testnet described in the guide you're following: https://github.com/lightiv/SkyNet/wiki/Akash-Seed-Node-Installation-Guide
* `ovrclk/net/latest` is referencing the previous CosmosSDK build of Akash; which produce `akashd` and `akashctl` binaries.
  * It was tagged to work with Akash [v0.7.8-rc3](https://github.com/ovrclk/net/commit/1060a653a9375c46262bc7eb2eaeda36fe3a29bc#diff-39305a873543ce7d1f9b395c20b7eb7615ef245c00a5c6d0d0bcc5b2db148323R1); releasing `akashd` & `akashctl`.
  * Unfortunately right now, `github.com/ovrclk/net/latest` is not interoperable with `github.com/ovrclk/akash:master`.

Sorry for the confusion, we're working on cleaning up and improving consistency of the documentation.

If you'd like to continue with that guide, pull the binaries from [v0.7.8-rc3](https://github.com/ovrclk/akash/releases/tag/v0.7.8-rc3), and they should match `net/latest`'s genesis.json formatting.
